version: "3.9"

services:
  product:
    build:
      context: ./backend/product-service
      dockerfile: Dockerfile
    image: sit722/product:dev
    container_name: product
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 5
    networks:
      - appnet

  order:
    build:
      context: ./backend/order-service
      dockerfile: Dockerfile
    image: sit722/order:dev
    container_name: order
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8081/health"]
      interval: 30s
      timeout: 3s
      retries: 5
    networks:
      - appnet

  customer:
    build:
      context: ./backend/customer-service
      dockerfile: Dockerfile
    image: sit722/customer:dev
    container_name: customer
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8082/health"]
      interval: 30s
      timeout: 3s
      retries: 5
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: sit722/frontend:static
    container_name: frontend
    ports:
      - "8088:80"
    depends_on:
      product:
        condition: service_healthy
      order:
        condition: service_healthy
      customer:
        condition: service_healthy
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
